languageCode = "fr"
languageName = "Fran√ßais"
weight = 1
title = "Mon Petit Poulailler"

[params]
  displayName = "FR"
  isoCode = "fr"
  rtl = false
  dateFormat = "2 January 2006"
  logo = "martin.png" 
  # C'est cette ligne ci-dessus qui est CRUCIALE pour Martin

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Accueil"
    url = "/"
    weight = 10

  [[menu.main]]
    identifier = "blog"
    name = "Le Poulailler"
    url = "/posts/"
    weight = 20
