languageName = "Français"
contentDir = "content"
weight = 1

[params]
  logo = "martin.png"
  # On injecte la mention Amazon ici car le thème affiche ce champ en priorité
  copyright = "© 2026 Mon Petit Poulailler - Tous droits réservés. | En tant que Partenaire Amazon, je réalise un bénéfice sur les achats remplissant les conditions requises."

  [params.footer]
    enable = true
    showCopyright = true
    showThemeNumber = false
    showSocial = true