disabled = false
languageCode = "fr"
languageName = "Français"
weight = 1
title = "Mon Petit Poulailler"

[params]
  displayName = "FR"
  isoCode = "fr"
  rtl = false
  dateFormat = "2 January 2006"
  description = "Conseils passionnés pour élever vos poules avec Martin et Julie."
 copyright = "En tant que Partenaire Amazon, je réalise un bénéfice sur les achats remplissant les conditions requises. | © 2025 Mon Petit Poulailler"

[params.author]
  name = "Martin"
  # image = "img/martin_logo.png" # À créer plus tard
  headline = "Menuisier passionné et expert en poulaillers"
  bio = "Martin partage ses astuces de menuisier pour offrir le meilleur confort à vos poules."