[[main]]
  name = "Accueil"
  pageRef = "/"
  weight = 10

[[main]]
  name = "Matériel"
  pageRef = "categories/materiel"
  weight = 20

[[main]]
  name = "Nutrition"
  pageRef = "categories/nutrition"
  weight = 30

[[main]]
  name = "Santé"
  pageRef = "categories/sante"
  weight = 40

[[main]]
  name = "Guides"
  pageRef = "categories/guides"
  weight = 50
