[[main]]
  name = "Accueil"
  url = "/"
  weight = 10

[[main]]
  name = "Nutrition"
  url = "/categories/nutrition/"
  weight = 20

[[main]]
  name = "Matériel"
  url = "/categories/materiel/"
  weight = 30

[[main]]
  name = "Santé & Hygiène"
  url = "/categories/sante/"
  weight = 40

[[main]]
  name = "Réglementation"
  url = "/categories/guides/"
  weight = 50

[[main]]
  name = "À Propos"
  url = "/about/"
  weight = 60
