# Configuration des param√®tres Blowfish
[appearance]
  showTaxonomies = true
  heroStyle = "basic"
  googleFonts = ["Quicksand", "Nunito"]
  fontHeading = "quicksand"
  fontBody = "nunito"

[header]
  logo = "images/martin.svg"
  # Pas de showLogo, pas de chichi. Juste le fichier.


